### PR TITLE
Hardcode content type for POST requests

### PR DESCRIPTION
**Pull request by tonyelhabr**
MLflow requires `Content-Type = "application/json"` for all POST requests.

image

### CODE REVIEW

**Review by michael-johnson314 — APPROVED** [review]

**Review by porterjames — APPROVED** [review]

**Comment by porterjames** [comment]
@tonyelhabr Any idea about the failed GitHub action? 

```
Error: Error: package or namespace load failed for 'testthat' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'R6' 2.5.0 is being loaded, but >= 2.5.1 is required
Execution halted
```

**Comment by tonyelhabr** [comment]
> @tonyelhabr Any idea about the failed GitHub action?
> 
> ```
> Error: Error: package or namespace load failed for 'testthat' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
>  namespace 'R6' 2.5.0 is being loaded, but >= 2.5.1 is required
> Execution halted
> ```

ugh, yes.

how about this--i'll revert internal bumping of mlflow until i get this fixed.

**Comment by mrkaye97** [comment]
😬 

yet another breaking change from the maintainers, whaddaya know

**Review by mrkaye97 — APPROVED** [review]

**Comment by tonyelhabr** [comment]
Tests pass on local. Current setup requires an instance of mlflow running at `http://localhost:5001` (see `MLFLOW_TRACKING_URI`.)

**Comment by tonyelhabr** [comment]
> Tests pass on local. Current setup requires an instance of mlflow running at `http://localhost:5001` (see `MLFLOW_TRACKING_URI`.)

I'll follow up at some point to fix the testing suite in the GHA.

**Pull request merged**
